### ISSUE TITLE
Value is being interpreted as column name

### ISSUE THREAD

**Issue by shreyansh-c** [Hiteshdon/mssql_connection#5]
void _login() async {
    String email = _emailController.text.trim();
    //String password = _passwordController.text.trim();

    String query = 'SELECT userId FROM login WHERE userId = "$email"';
    print(query);
    String result = await widget.mssqlConnection.getData(query);
    print(result);

    if (result.isNotEmpty) {
      setState(() {
        _message = 'Login successful!';
      });
      Future.delayed(const Duration(seconds: 1), () {
        Navigator.of(context).pushReplacement(
            MaterialPageRoute(builder: (context) => const HomeScreen()));
      });
    } else {
      setState(() {
        _message = 'Invalid email or password';
      });
    }
  }

the above code throws an expection PlatformException (PlatformException(DATABASE_ERROR, Invalid column name 'abhinavswami9@gmail.com'., null, null))
<img width="1440" alt="image" src="https://github.com/Hiteshdon/mssql_connection/assets/90549605/7a7fa64e-08c6-4ff5-9947-c99f194e8762">

**Comment by farooq958** [comment]
String escapedEmail = "'$email'"; use it like this

**Comment by Hiteshdon** [comment]
The issue happens because the email variable isn't enclosed in single quotes in the query. You can fix it by updating the query like this:

```dart
String query = "SELECT userId FROM login WHERE userId = '$email'";
```
This ensures the email is treated as a string, avoiding the `Invalid column name` error
